/*

Welcome to the SadConsole demo template! This template is the project I use to test
SadConsole as I create new features. It's also a great way to see how to write code
that uses different SadConsole features.

This template will be updated with each release of SadConsole.

=========================================================
Important things you should know about this template
=========================================================

This project generated by this template imports the following namespaces into every
code file:

- SadConsole
- SadRogue.Primitives

Additionally, the SadConsole.Console type is mapped as Console so that it doesn't
conflict with System.Console if you import the System namespace.

Each Demo code file in the project contains two classes. The first is the class
that implements the IDemo interface. This class is what is used by the demo list
box so that you can preview each demo object. The second class is the actual console
demo code, which you can reuse in your own project.

*/

using System.Numerics;
using Hexa.NET.ImGui;
using SadConsole.Configuration;
using SadConsole.Examples;
using SadConsole.ImGuiSystem.Rendering;
using SadConsole.UI;

#if FNA
Settings.WindowTitle = "SadConsole Examples (FNA)";
#elif MONOGAME
Settings.WindowTitle = "SadConsole Examples (MONOGAME)";
#elif SFML
Settings.WindowTitle = "SadConsole Examples (SFML)";
#endif

Builder
    .GetBuilder()
    .ConfigureFonts((config, host) =>
    {
        // FullHD default: <= 1920x1870
        IFont.Sizes defaultFontSize = IFont.Sizes.One;

        host.GetDeviceScreenSize(out int width, out int height);

        // QHD (aka 2k)
        if (width > 1920 && height > 1080)
            defaultFontSize = IFont.Sizes.Two;

        //// Most likely 4k
        //if (width > 2560 && height > 1440)
        //    defaultFontSize = IFont.Sizes.Four;

        config.DefaultFontSize = defaultFontSize;
        config.UseExtendedFont = true;
        config.AddExtraFonts("Res/Fonts/dbyte_2x.font");
    })
    
    .SetStartingScreen<RootScreen>()
    .IsStartingScreenFocused(false) // Don't want RootScreen to be focused because RootScreen automatically focuses the selected demo console
    .SetWindowSizeInCells(GameSettings.GAME_WIDTH, GameSettings.GAME_HEIGHT)
    .ConfigureWindow((config, builder, host) =>
    {
        config.SetWindowSizeInCells(GameSettings.GAME_WIDTH, GameSettings.GAME_HEIGHT, false); // zoom mode is false
        config.BorderlessWindowedFullscreen = true;
        config.Fullscreen = true;
    })
    //.SetSplashScreen<SadConsole.SplashScreens.Ansi1>()
    .PopupGlyphPicker(SadConsole.Input.Keys.F11)
    .EnableImGuiDebugger(SadConsole.Input.Keys.F12, startupAction: component =>
    {
        SadConsole.Debug.ImGuiDebugger.Instance.Opened += (firstTime, renderer) =>
        {
            if (firstTime)
                SadConsole.Debug.ImGuiDebugger.Instance.DebuggerUI.Add(new ImGuiWindow1());
        };
    })
    .OnStart((sender, host) => { host.RootComponents.Add(new RootKeyboardHooksRootComponent()); })
    .Run();

internal class ImGuiWindow1 : SadConsole.ImGuiSystem.ImGuiObjectBase
{
    private Vector3 _clearColor = Color.White.ToVector3();

    public override void BuildUI(ImGuiRenderer renderer)
    {
        if (ImGui.Begin("Operations"))
        {
            // Run random garbage fill
            if (ImGui.Button("Randomize"))
                ((IScreenSurface)GameHost.Instance.Screen!.Children[0]).Surface.FillWithRandomGarbage(255);

            // Add a random box
            if (ImGui.Button("Add box"))
            {
                IScreenSurface surface = (IScreenSurface)GameHost.Instance.Screen!.Children[0];

                int x = GameHost.Instance.Random.Next(0, surface.Surface.Width - 10);
                int y = GameHost.Instance.Random.Next(0, surface.Surface.Height - 10);

                Rectangle area = new(x, y,
                                     GameHost.Instance.Random.Next(5, surface.Surface.Width - x),
                                     GameHost.Instance.Random.Next(4, surface.Surface.Height - y));

                ShapeParameters shape = ShapeParameters.CreateStyledBoxFilled(ICellSurface.ConnectedLineThin,
                                                                              new ColoredGlyph(Color.White.GetRandomColor(GameHost.Instance.Random),
                                                                                               Color.White.GetRandomColor(GameHost.Instance.Random)),
                                                                              new ColoredGlyph(Color.White.GetRandomColor(GameHost.Instance.Random),
                                                                                               Color.White.GetRandomColor(GameHost.Instance.Random))
                                                                              );

                SadConsole.Instructions.AnimatedBoxGrow box = new(area, TimeSpan.FromSeconds(0.5d), shape);
                box.RemoveOnFinished = true;
                surface.SadComponents.Add(box);
            }

            // Color picking control. When the color changes, fill the surface
            ImGui.Separator();
            ImGui.Text("Set all cell backgrounds");
            ImGui.SetNextItemWidth(150);
            if (ImGui.ColorPicker3("##clearcolor", ref _clearColor, ImGuiColorEditFlags.NoInputs | ImGuiColorEditFlags.NoSidePreview))
                ((IScreenSurface)GameHost.Instance.Screen!.Children[0]).Surface.Fill(background: _clearColor.ToColor());
        }
        ImGui.End();
    }
}
