/*

Welcome to the SadConsole demo template! This template is the project I use to test
SadConsole as I create new features. It's also a great way to see how to write code
that uses different SadConsole features.

This template will be updated with each release of SadConsole.

=========================================================
Important things you should know about this template
=========================================================

This project generated by this template imports the following namespaces into every
code file:

- SadConsole
- SadRogue.Primitives

Additionally, the SadConsole.Console type is mapped as Console so that it doesn't
conflict with System.Console if you import the System namespace.

Each Demo code file in the project contains two classes. The first is the class
that implements the IDemo interface. This class is what is used by the demo list
box so that you can preview each demo object. The second class is the actual console
demo code, which you can reuse in your own project.

*/

using SadConsole.Examples;
using SadConsole.Configuration;

#if FNA
Settings.WindowTitle = "SadConsole Examples (FNA)";
#elif MONOGAME
Settings.WindowTitle = "SadConsole Examples (MONOGAME)";
#elif SFML
Settings.WindowTitle = "SadConsole Examples (SFML)";
#endif

Builder
    .GetBuilder()
    .ConfigureFonts((config, host) =>
    {
        // FullHD default: <= 1920x1870
        IFont.Sizes defaultFontSize = IFont.Sizes.One;

        host.GetDeviceScreenSize(out int width, out int height);

        // QHD (aka 2k)
        if (width > 1920 && height > 1080)
            defaultFontSize = IFont.Sizes.Two;

        // Most likely 4k
        if (width > 2560 && height > 1440)
            defaultFontSize = IFont.Sizes.Four;

        config.DefaultFontSize = defaultFontSize;
        config.UseExtendedFont = true;
    })
    
    .SetStartingScreen<RootScreen>()
    .IsStartingScreenFocused(false) // Don't want RootScreen to be focused because RootScreen automatically focuses the selected demo console
    .SetWindowSizeInCells(GameSettings.GAME_WIDTH, GameSettings.GAME_HEIGHT)
    .SetSplashScreen<SadConsole.SplashScreens.Ansi1>()
    //.EnableImGuiDebugger(SadConsole.Input.Keys.F5)
    .PopupGlyphPicker(SadConsole.Input.Keys.F11)
    .Run();
